version: '3.3'

services:
  application:
    container_name: "application"
    build:
      context: './api_application'
      target: dev
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - "db"
    command: "yarn dev"

  scraping:
    container_name: "scraping"
    build:
      context: './api_scraping'
      target: dev
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    depends_on:
      - "db"
    command: "yarn dev"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: docker
